vendor: libbfqio: Add missing header files
Fixes the following errors:
error: call to undeclared library function 'strerror'
error: use of undeclared identifier 'errno'